
name: Deploy Solana Bot


on:
push:
branches: [ main ]


jobs:
build-and-deploy:
runs-on: ubuntu-latest


steps:
- name: Checkout
uses: actions/checkout@v4


- name: Setup Node
uses: actions/setup-node@v4
with:
node-version: 18


- name: Install deps
run: npm ci


- name: Build Docker image
run: docker build -t solana-trading-bot .


- name: Push to Docker Hub
uses: docker/login-action@v3
with:
username: ${{ secrets.DOCKERHUB_USERNAME }}
password: ${{ secrets.DOCKERHUB_TOKEN }}


- run: |
docker tag solana-trading-bot ${{ secrets.DOCKERHUB_USERNAME }}/solana-trading-bot:latest
docker push ${{ secrets.DOCKERHUB_USERNAME }}/solana-trading-bot:latest


- name: Deploy via SSH
uses: appleboy/ssh-action@v1.2.0
with:
host: ${{ secrets.SERVER_HOST }}
username: ${{ secrets.SERVER_USER }}
key: ${{ secrets.SERVER_SSH_KEY }}
script: |
docker pull ${{ secrets.DOCKERHUB_USERNAME }}/solana-trading-bot:latest
docker stop solana-trading-bot || true
docker rm solana-trading-bot || true
docker run -d --restart always --env-file .env --name solana-trading-bot ${{ secrets.DOCKERHUB_USERNAME }}/solana-trading-bot:latest
